@startuml
class klasa {
- id: int
- strings: List<List<String>>
- collections: List<? extends java.util.Collection>
+ Account(arg0: int, arg1: AccountHolder, arg2: Map)
+ getId(): int
+ setId(arg0: int): void
+ getHolderID(): AccountHolder
+ setHolderID(arg0: AccountHolder): void
+ randomMathod(arg0: List<? extends com.patryk.Maybe>): void
+ getMaybeMap(): Map<Integer, Maybe>
+ setMaybeMap(arg0: Map<Integer, Maybe>): void
}


@enduml